import { useEffect, useState } from "react";

const C = { blue: "#1877F2", navy: "#071A33", yellow: "#FFD83D", ink: "#10233F", muted: "#627087", soft: "#F5F8FC", line: "#E5ECF5", white: "#FFFFFF" };

const Icon = ({ name, size = 20 }) => {
  const paths = {
    arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    target: <><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/></>,
    clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    chart: <><path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/></>,
    pin: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
    spark: <><path d="m12 3 1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3Z"/><path d="m19 15 .8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15Z"/></>,
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
    menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>,
    x: <><path d="m6 6 12 12M18 6 6 18"/></>
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
};

const features = [
  ["clock", "Présence & ponctualité", "Visualisez les arrivées, départs, retards, absences et missions sans multiplier les fichiers de suivi."],
  ["target", "Tâches & objectifs", "Assignez, suivez et mesurez l’exécution. Chaque action devient une donnée claire et exploitable."],
  ["chart", "Performance mesurable", "Transformez l’activité quotidienne en indicateurs lisibles pour reconnaître le mérite et agir plus vite."],
  ["spark", "Proactivité", "Faites remonter les initiatives, les contributions et les signaux qui restent habituellement invisibles."],
  ["pin", "Pilotage multisite", "Gardez une vision cohérente de vos équipes, même lorsque vous n’êtes pas physiquement sur place."],
  ["shield", "Décisions documentées", "Appuyez vos revues RH sur un historique structuré plutôt que sur des impressions ou des souvenirs."],
];

export default function LandingPage({ onEntrer }) {
  const [menu, setMenu] = useState(false);
  useEffect(() => {
    const onScroll = () => document.documentElement.style.setProperty("--bc-scroll", `${window.scrollY}px`);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const entrer = () => onEntrer?.();
  const go = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenu(false); };

  return <div className="bc-site">
    <style>{`
      *{box-sizing:border-box}.bc-site{font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:${C.ink};background:#fff;overflow:hidden}.bc-site button,.bc-site a{font:inherit}.bc-wrap{width:min(1180px,calc(100% - 44px));margin:auto}.bc-nav{height:78px;display:flex;align-items:center;justify-content:space-between;position:relative;z-index:4}.bc-logo{display:flex;align-items:center;gap:11px;font-weight:850;font-size:21px;letter-spacing:-.6px;color:${C.navy}}.bc-logo-mark{width:36px;height:36px;border-radius:12px;background:${C.blue};display:grid;place-items:center;color:#fff;box-shadow:0 8px 22px rgba(24,119,242,.24);position:relative}.bc-logo-mark:after{content:"";width:8px;height:8px;background:${C.yellow};border-radius:50%;position:absolute;right:-2px;top:-2px;border:3px solid white}.bc-links{display:flex;align-items:center;gap:30px}.bc-links button{border:0;background:none;color:#536176;cursor:pointer;font-size:14px;font-weight:600}.bc-links button:hover{color:${C.blue}}.bc-btn{border:0;border-radius:13px;padding:13px 19px;font-weight:750;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:9px;transition:.22s ease}.bc-btn:hover{transform:translateY(-2px)}.bc-primary{background:${C.blue};color:#fff;box-shadow:0 12px 28px rgba(24,119,242,.23)}.bc-secondary{background:#fff;color:${C.navy};border:1px solid ${C.line};box-shadow:0 8px 25px rgba(16,35,63,.06)}.bc-nav-cta{padding:11px 16px}.bc-menu{display:none;border:0;background:none;color:${C.navy}}
      .bc-hero{position:relative;background:radial-gradient(circle at 8% 10%,rgba(255,216,61,.16),transparent 28%),radial-gradient(circle at 88% 30%,rgba(24,119,242,.12),transparent 32%),linear-gradient(180deg,#fff 0%,#F8FBFF 100%);padding-bottom:76px}.bc-hero:after{content:"";position:absolute;left:-5%;right:-5%;bottom:-38px;height:75px;background:white;border-radius:50% 50% 0 0/100% 100% 0 0}.bc-hero-grid{min-height:660px;display:grid;grid-template-columns:.94fr 1.06fr;align-items:center;gap:58px;padding:48px 0 70px}.bc-kicker{display:inline-flex;align-items:center;gap:8px;background:#EDF5FF;color:${C.blue};border:1px solid #D7E9FF;border-radius:999px;padding:8px 12px;font-size:12px;font-weight:800;letter-spacing:.04em;text-transform:uppercase}.bc-kicker i{width:7px;height:7px;border-radius:50%;background:${C.yellow};box-shadow:0 0 0 4px rgba(255,216,61,.2)}.bc-hero h1{font-size:clamp(46px,5.3vw,72px);line-height:.98;letter-spacing:-3.8px;margin:22px 0 24px;color:${C.navy};max-width:650px}.bc-hero h1 span{color:${C.blue}}.bc-lead{font-size:18px;line-height:1.75;color:${C.muted};max-width:590px;margin:0 0 29px}.bc-actions{display:flex;gap:12px;flex-wrap:wrap}.bc-proof{display:flex;align-items:center;gap:20px;margin-top:32px;color:#6C788B;font-size:12px;font-weight:650}.bc-proof span{display:flex;align-items:center;gap:7px}.bc-proof svg{color:#2B9B68}.bc-visual{position:relative}.bc-photo{height:535px;border-radius:34px;overflow:hidden;box-shadow:0 35px 80px rgba(7,26,51,.18);position:relative}.bc-photo img{width:100%;height:100%;object-fit:cover}.bc-photo:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,rgba(7,26,51,.2))}.bc-float{position:absolute;background:rgba(255,255,255,.94);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.8);box-shadow:0 18px 45px rgba(7,26,51,.16);border-radius:18px;padding:15px 17px;z-index:2}.bc-float.a{left:-42px;top:56px}.bc-float.b{right:-30px;bottom:45px}.bc-float small{display:block;color:#788397;font-size:10px;text-transform:uppercase;font-weight:800;letter-spacing:.08em;margin-bottom:5px}.bc-float strong{font-size:20px;color:${C.navy}}.bc-float .up{color:#209765;font-size:12px;font-weight:750;margin-left:8px}.bc-dots{position:absolute;width:120px;height:120px;right:-35px;top:-25px;background-image:radial-gradient(${C.yellow} 2px,transparent 2px);background-size:14px 14px;opacity:.8}
      .bc-strip{padding:42px 0 60px}.bc-strip-inner{display:grid;grid-template-columns:1.15fr repeat(3,1fr);gap:20px;align-items:center;border-bottom:1px solid ${C.line};padding-bottom:38px}.bc-strip-title{font-weight:800;color:${C.navy};font-size:15px}.bc-stat strong{display:block;font-size:27px;color:${C.navy};letter-spacing:-1px}.bc-stat span{font-size:12px;color:${C.muted}}
      .bc-section{padding:100px 0}.bc-head{max-width:700px;margin-bottom:48px}.bc-eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.12em;font-weight:850;color:${C.blue};margin-bottom:12px}.bc-title{font-size:clamp(34px,4vw,52px);letter-spacing:-2.2px;line-height:1.05;margin:0 0 17px;color:${C.navy}}.bc-sub{font-size:17px;line-height:1.7;color:${C.muted};margin:0}.bc-features{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.bc-card{padding:28px;border:1px solid ${C.line};border-radius:22px;background:#fff;transition:.25s ease}.bc-card:hover{transform:translateY(-5px);box-shadow:0 22px 50px rgba(7,26,51,.09);border-color:#D8E7FA}.bc-icon{width:44px;height:44px;border-radius:14px;background:#EDF5FF;color:${C.blue};display:grid;place-items:center;margin-bottom:24px}.bc-card:nth-child(2) .bc-icon,.bc-card:nth-child(5) .bc-icon{background:#FFF8D8;color:#B38700}.bc-card h3{font-size:18px;margin:0 0 10px;color:${C.navy}}.bc-card p{font-size:14px;line-height:1.65;color:${C.muted};margin:0}
      .bc-dark{background:${C.navy};color:#fff;position:relative;overflow:hidden}.bc-dark:before{content:"";position:absolute;width:520px;height:520px;border:1px solid rgba(255,255,255,.07);border-radius:50%;right:-160px;top:-240px;box-shadow:0 0 0 80px rgba(255,255,255,.025),0 0 0 160px rgba(255,255,255,.018)}.bc-split{display:grid;grid-template-columns:1fr 1fr;gap:72px;align-items:center}.bc-dark .bc-title{color:#fff}.bc-dark .bc-sub{color:#B9C5D4}.bc-dark .bc-eyebrow{color:${C.yellow}}.bc-image-stack{position:relative;height:540px}.bc-image-stack .main{width:88%;height:470px;object-fit:cover;border-radius:28px;position:absolute;right:0;top:0}.bc-image-stack .mini{width:48%;height:230px;object-fit:cover;border:8px solid ${C.navy};border-radius:24px;position:absolute;left:0;bottom:0;box-shadow:0 22px 50px rgba(0,0,0,.25)}.bc-list{display:grid;gap:18px;margin-top:30px}.bc-list div{display:flex;gap:13px;align-items:flex-start}.bc-check{width:26px;height:26px;min-width:26px;border-radius:8px;background:rgba(255,216,61,.13);color:${C.yellow};display:grid;place-items:center}.bc-list strong{display:block;font-size:14px;margin:1px 0 4px}.bc-list span{font-size:13px;color:#AEBBCD;line-height:1.5}
      .bc-showcase{background:${C.soft}}.bc-show-grid{display:grid;grid-template-columns:.92fr 1.08fr;gap:60px;align-items:center}.bc-show-img{height:570px;border-radius:30px;overflow:hidden;position:relative}.bc-show-img img{width:100%;height:100%;object-fit:cover}.bc-show-img:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,rgba(7,26,51,.35))}.bc-quote{position:absolute;left:25px;right:25px;bottom:25px;background:rgba(255,255,255,.92);backdrop-filter:blur(12px);border-radius:18px;padding:20px;z-index:2}.bc-quote strong{display:block;color:${C.navy};font-size:18px;margin-bottom:5px}.bc-quote span{font-size:12px;color:${C.muted}}.bc-steps{display:grid;gap:12px;margin-top:30px}.bc-step{display:grid;grid-template-columns:48px 1fr;gap:15px;padding:17px;border-radius:17px;border:1px solid transparent}.bc-step:hover{background:#fff;border-color:${C.line};box-shadow:0 12px 30px rgba(7,26,51,.05)}.bc-num{width:42px;height:42px;border-radius:13px;background:${C.navy};color:#fff;display:grid;place-items:center;font-weight:800}.bc-step h4{margin:2px 0 5px;font-size:15px;color:${C.navy}}.bc-step p{margin:0;color:${C.muted};font-size:13px;line-height:1.55}
      .bc-banner{padding:80px 0}.bc-banner-box{min-height:370px;border-radius:32px;overflow:hidden;position:relative;display:flex;align-items:center;padding:55px;background:${C.navy}}.bc-banner-box>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.35}.bc-banner-box:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,${C.navy} 5%,rgba(7,26,51,.9) 42%,rgba(7,26,51,.28) 100%)}.bc-banner-content{position:relative;z-index:2;max-width:620px}.bc-banner h2{color:#fff;font-size:clamp(34px,4vw,50px);letter-spacing:-2px;line-height:1.04;margin:0 0 16px}.bc-banner p{color:#C2CDDA;line-height:1.65;margin:0 0 25px}.bc-yellow{background:${C.yellow};color:${C.navy};box-shadow:0 12px 28px rgba(255,216,61,.2)}
      .bc-footer{background:#06172D;color:#9BAABC;padding:54px 0 28px}.bc-footer-grid{display:grid;grid-template-columns:1.6fr 1fr 1fr;gap:50px;padding-bottom:38px}.bc-footer .bc-logo{color:#fff}.bc-footer p{font-size:13px;line-height:1.65;max-width:390px}.bc-footer h4{color:#fff;font-size:13px;margin:0 0 16px}.bc-footer button{display:block;border:0;background:none;color:#9BAABC;padding:5px 0;cursor:pointer;font-size:13px}.bc-footer button:hover{color:#fff}.bc-copy{border-top:1px solid rgba(255,255,255,.08);padding-top:22px;font-size:11px;display:flex;justify-content:space-between;gap:20px}
      @media(max-width:900px){.bc-links{display:none}.bc-menu{display:block}.bc-links.open{display:flex;position:absolute;top:70px;left:0;right:0;background:#fff;border:1px solid ${C.line};border-radius:18px;padding:18px;flex-direction:column;align-items:stretch;box-shadow:0 20px 50px rgba(7,26,51,.12)}.bc-hero-grid,.bc-split,.bc-show-grid{grid-template-columns:1fr}.bc-hero-grid{padding-top:25px}.bc-hero h1{letter-spacing:-2.7px}.bc-visual{margin:0 25px}.bc-features{grid-template-columns:repeat(2,1fr)}.bc-strip-inner{grid-template-columns:1fr 1fr}.bc-strip-title{grid-column:1/-1}.bc-split{gap:40px}.bc-footer-grid{grid-template-columns:1fr 1fr}.bc-footer-grid>div:first-child{grid-column:1/-1}}
      @media(max-width:600px){.bc-wrap{width:min(100% - 28px,1180px)}.bc-nav{height:68px}.bc-hero-grid{min-height:auto;gap:38px;padding-bottom:40px}.bc-hero h1{font-size:43px;letter-spacing:-2.4px}.bc-lead{font-size:16px}.bc-actions .bc-btn{width:100%}.bc-proof{flex-direction:column;align-items:flex-start;gap:8px}.bc-photo{height:420px;border-radius:24px}.bc-visual{margin:0}.bc-float.a{left:-7px;top:25px}.bc-float.b{right:-7px;bottom:20px}.bc-dots{display:none}.bc-strip-inner{grid-template-columns:1fr 1fr}.bc-section{padding:72px 0}.bc-features{grid-template-columns:1fr}.bc-image-stack{height:440px}.bc-image-stack .main{height:380px;width:92%}.bc-image-stack .mini{height:180px;width:55%}.bc-show-img{height:460px}.bc-banner{padding:55px 0}.bc-banner-box{padding:32px 25px;min-height:420px}.bc-banner-box:after{background:linear-gradient(90deg,rgba(7,26,51,.97),rgba(7,26,51,.65))}.bc-footer-grid{grid-template-columns:1fr}.bc-footer-grid>div:first-child{grid-column:auto}.bc-copy{flex-direction:column}.bc-title{letter-spacing:-1.6px}}
    `}</style>

    <section className="bc-hero">
      <div className="bc-wrap">
        <nav className="bc-nav">
          <div className="bc-logo"><span className="bc-logo-mark"><Icon name="chart" size={19}/></span> BossClever</div>
          <div className={`bc-links ${menu ? "open" : ""}`}>
            <button onClick={() => go("solution")}>Solution</button><button onClick={() => go("pilotage")}>Pilotage</button><button onClick={() => go("methode")}>Comment ça marche</button>
            <button className="bc-btn bc-primary bc-nav-cta" onClick={entrer}>Se connecter <Icon name="arrow" size={16}/></button>
          </div>
          <button className="bc-menu" onClick={() => setMenu(!menu)}><Icon name={menu ? "x" : "menu"} size={25}/></button>
        </nav>

        <div className="bc-hero-grid">
          <div>
            <div className="bc-kicker"><i/> La performance devient visible</div>
            <h1>L’entreprise sous contrôle. <span>Même quand vous n’y êtes pas.</span></h1>
            <p className="bc-lead">BossClever rassemble présence, tâches, objectifs, rapports et performance dans un seul espace pour vous donner une lecture claire de la réalité opérationnelle.</p>
            <div className="bc-actions"><button className="bc-btn bc-primary" onClick={entrer}>Accéder à BossClever <Icon name="arrow" size={18}/></button><button className="bc-btn bc-secondary" onClick={() => go("solution")}>Découvrir la solution</button></div>
            <div className="bc-proof"><span><Icon name="check" size={15}/> Décisions documentées</span><span><Icon name="check" size={15}/> Suivi centralisé</span><span><Icon name="check" size={15}/> Vision manager</span></div>
          </div>
          <div className="bc-visual">
            <div className="bc-dots"/><div className="bc-photo"><img src="/images/boss-hero.jpg" alt="Manager présentant des indicateurs de performance à son équipe"/></div>
            <div className="bc-float a"><small>Vue dirigeant</small><strong>360°</strong><span className="up">● En direct</span></div>
            <div className="bc-float b"><small>Performance</small><strong>Voir. Mesurer. Décider.</strong></div>
          </div>
        </div>
      </div>
    </section>

    <div className="bc-wrap bc-strip"><div className="bc-strip-inner"><div className="bc-strip-title">Un seul cockpit pour piloter l’essentiel.</div><div className="bc-stat"><strong>01</strong><span>Présence & ponctualité</span></div><div className="bc-stat"><strong>02</strong><span>Exécution & objectifs</span></div><div className="bc-stat"><strong>03</strong><span>Performance & mérite</span></div></div></div>

    <section id="solution" className="bc-section"><div className="bc-wrap"><div className="bc-head"><div className="bc-eyebrow">La solution BossClever</div><h2 className="bc-title">Tout ce qui compte. Enfin au même endroit.</h2><p className="bc-sub">Le management quotidien produit beaucoup de signaux. BossClever les structure pour que le dirigeant comprenne rapidement ce qui avance, ce qui bloque et qui contribue réellement.</p></div><div className="bc-features">{features.map(([i,t,d])=><div className="bc-card" key={t}><div className="bc-icon"><Icon name={i}/></div><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>

    <section id="pilotage" className="bc-section bc-dark"><div className="bc-wrap bc-split"><div><div className="bc-eyebrow">Pilotage manager</div><h2 className="bc-title">Vous n’avez pas besoin d’être partout pour savoir.</h2><p className="bc-sub">BossClever rapproche le dirigeant du terrain en transformant l’activité de ses équipes en informations compréhensibles, consultables et comparables.</p><div className="bc-list"><div><span className="bc-check"><Icon name="check" size={15}/></span><p><strong>Une lecture immédiate de l’exécution</strong><span>Repérez les tâches en cours, les échéances, les retards et les résultats déclarés.</span></p></div><div><span className="bc-check"><Icon name="check" size={15}/></span><p><strong>Des décisions RH mieux étayées</strong><span>Valorisez la régularité, l’atteinte des objectifs et les initiatives sur des traces consultables.</span></p></div><div><span className="bc-check"><Icon name="check" size={15}/></span><p><strong>Une gouvernance plus lisible</strong><span>Managers, employés et co-administrateurs travaillent dans des espaces adaptés à leur rôle.</span></p></div></div></div><div className="bc-image-stack"><img className="main" src="/images/boss-pilotage.jpg" alt="Équipe analysant une stratégie d'entreprise"/><img className="mini" src="/images/boss-equipe.jpg" alt="Équipe autour d'un ordinateur"/></div></div></section>

    <section id="methode" className="bc-section bc-showcase"><div className="bc-wrap bc-show-grid"><div className="bc-show-img"><img src="/images/boss-manager.jpg" alt="Manager dans un environnement de travail"/><div className="bc-quote"><strong>Le mérite ne devrait pas dépendre de la mémoire.</strong><span>BossClever construit un historique de travail exploitable dans le temps.</span></div></div><div><div className="bc-eyebrow">Comment ça marche</div><h2 className="bc-title">Du travail quotidien à une vision décisionnelle.</h2><p className="bc-sub">Une logique simple, conçue pour s’intégrer au fonctionnement réel de l’entreprise sans alourdir le quotidien.</p><div className="bc-steps"><div className="bc-step"><span className="bc-num">1</span><div><h4>Organiser</h4><p>Créez vos équipes, rôles, sites, horaires, tâches et objectifs.</p></div></div><div className="bc-step"><span className="bc-num">2</span><div><h4>Suivre</h4><p>Centralisez pointages, réalisations, rapports, initiatives et délais.</p></div></div><div className="bc-step"><span className="bc-num">3</span><div><h4>Mesurer</h4><p>Faites ressortir les tendances, écarts et contributions avec des critères structurés.</p></div></div><div className="bc-step"><span className="bc-num">4</span><div><h4>Décider</h4><p>Appuyez vos échanges et décisions managériales sur un historique consultable.</p></div></div></div></div></div></section>

    <section className="bc-banner"><div className="bc-wrap"><div className="bc-banner-box"><img src="/images/boss-strategie.jpg" alt="Équipe travaillant sur une stratégie"/><div className="bc-banner-content"><div className="bc-eyebrow">BossClever × Clever Entreprises</div><h2>Transformez l’activité de vos équipes en décisions plus intelligentes.</h2><p>Une plateforme pensée pour les dirigeants et managers qui veulent plus de clarté, plus d’équité et moins de zones d’ombre.</p><button className="bc-btn bc-yellow" onClick={entrer}>Entrer dans BossClever <Icon name="arrow" size={18}/></button></div></div></div></section>

    <footer className="bc-footer"><div className="bc-wrap"><div className="bc-footer-grid"><div><div className="bc-logo"><span className="bc-logo-mark"><Icon name="chart" size={19}/></span> BossClever</div><p>Solution SaaS de pilotage de la performance développée par Clever Entreprises. Voir. Mesurer. Décider.</p></div><div><h4>Produit</h4><button onClick={() => go("solution")}>Fonctionnalités</button><button onClick={() => go("pilotage")}>Pilotage manager</button><button onClick={() => go("methode")}>Méthode</button></div><div><h4>Accès</h4><button onClick={entrer}>Connexion</button><button onClick={() => { window.location.hash="#cgu"; }}>Conditions d’utilisation</button><button onClick={() => { window.location.hash="#confidentialite"; }}>Confidentialité</button></div></div><div className="bc-copy"><span>© 2026 Clever Entreprises. Tous droits réservés.</span><span>BossClever — Piloter. Mesurer. Décider.</span></div></div></footer>
  </div>;
}
